server:
  port: 9020

spring:
  data:
    mongodb:
      uri: mongodb://localhost:27017/bootcamp51?authSource=admin

rutaApiClient: "http://localhost:9010/bootcamp51/ms/client"
reintentosApiClient: 3
timeIntervalApiClient: 3

