server:
  port: 9020
  servlet:
    context-path: /bootcamp51/ms/product

spring:
  data:
    mongodb:
      uri: mongodb://192.168.1.51:27017/bootcamp51?authSource=admin

rutaApiClient: "http://localhost:9010/bootcamp51/ms/client"
retryApiClient: 3
timeIntervalApiClient: 3

